//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public string Item { get; set; }
        public string Amount { get; set; }
        public int CustomerID { get; set; }
    }
}
