//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Amount { get; set; }
        public string Specification { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Product Products1 { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Category Category { get; set; }
    }
}
